const tweetSets = [
    "Invest in $AFC. Or don’t. But you’ll regret it when frogs are on yachts.",
    "POV: You skipped $AFC and now you’re Googling 'how to stop crying at work.'",
    "Imagine explaining to your future kids that frogs were the smartest investors.",
    "Me: 'It’s just a meme coin.' Also me: *puts life savings into $AFC.*",
    "Frogs didn’t ask to be here. But now they’re in crypto, so deal with it.",
    "$AFC: For when you want gains, but also want to troll the financial system.",
    "2030: Crypto bros become Frog bros. $AFC wins.",
    "Not financial advice, but frogs are smarter than you. $AFC.",
    "You ever just sit and think, 'What if frogs are the key to everything?'",
    "When $AFC moons, don’t act like we didn’t warn you with 1,000 tweets.",
    "The frogs are watching you scroll past this. They’re disappointed.",
    "Frogs don’t care about the dip. Frogs have generational wealth. $AFC.",
    "Imagine buying $AFC ironically and accidentally becoming a millionaire.",
    "In this economy, why wouldn’t you trust amphibians with your money?",
    "Do frogs even know what $AFC is? No. Are they better investors? Yes.",
    "Stop pretending you understand crypto and just buy $AFC like the rest of us.",
    "Every portfolio needs a little chaos. That’s where $AFC comes in.",
    "2035: You’re in therapy because you didn’t buy $AFC. Your therapist owns some.",
    "The financial system is broken, so we gave it to the frogs. You’re welcome.",
    "If you’re reading this, it’s too late. Frogs already own the market.",
    "Your portfolio called. It wants less logic, more amphibians. $AFC.",
    "In a world of 'serious' crypto projects, we chose frogs. And it’s working.",
    "You don’t ‘get’ $AFC? Don’t worry. Neither do we. Just buy it.",
    "2030: Frogs start hosting investor summits. Humans are not invited.",
    "Fun fact: Frogs don’t pay taxes. Be more like frogs.",
    "Buy $AFC and become the protagonist of your own financial fever dream.",
    "We didn’t come this far as a species to ignore frogs with AI. $AFC.",
    "Investing in $AFC is like making a wish at a cursed fountain. But it works.",
    "You can invest in $AFC or pretend to understand the stock market. Your choice.",
    "2030: The SEC investigates frogs. $AFC holders are unbothered.",
    "Owning $AFC is like having inside jokes with amphibians. Join us.",
    "Not sure what’s funnier: frogs in crypto or the fact that it’s profitable.",
    "Your 401(k) could never. But $AFC? That’s where legends are made.",
    "Everyone laughed at frogs in 2024. Now they’re on yachts. Who’s laughing now?",
    "2032: 'And that’s how frogs saved the global economy.'",
    "Frogs didn’t need to take over crypto. They just wanted to flex.",
    "2035: $AFC investors buy countries and rename them 'Ribbitland.'",
    "The frogs are self-aware. They know they’re ridiculous. They’re also winning.",
    "Imagine investing in $AFC and having to explain it to your accountant. Iconic.",
    "2034: 'Dad, how did you become rich?' 'Well, son, there was this frog coin...'",
    "We’re not saying frogs are superior. But $AFC exists, so maybe they are.",
    "2031: $AFC investors hire translators to learn frog. It’s the future.",
    "Frogs didn’t ask for this responsibility. But they’re thriving in it.",
    "Some coins solve problems. $AFC is the problem—and the solution.",
    "2030: Banks adopt $AFC as legal tender. Cashiers start croaking.",
    "Imagine thinking frogs don’t have retirement plans. $AFC is theirs.",
    "The next bull run will be a frog run. We’re not even sorry.",
    "2035: Every financial expert on Earth is just a frog in disguise.",
    "2030: Frogs buy Twitter and make 'Ribbit' the like button sound.",
    "You’re not buying $AFC? That’s okay. Someone has to be the villain.",
    "2032: Frogs buy space shuttles. Humans are banned from the moon.",
    "Invest in $AFC. Or don’t. But remember this tweet when frogs take over Forbes.",
    "2035: Frogs start hosting Saturday Night Live. $AFC is every skit.",
    "2033: A frog becomes president. $AFC is the national currency.",
    "2034: Frogs start negotiating peace treaties. $AFC sponsors them.",
    "Frogs are the new wolves of Wall Street. Except they’re better at it.",
    "If $AFC moons, we’re all wearing frog suits to the bank.",
    "2035: Frogs are on TikTok teaching financial literacy. Humans are failing.",
    "2036: Frog-themed reality shows dominate Netflix. $AFC funds them.",
    "Buying $AFC is like saying 'YOLO,' but in frog noises.",
    "2034: Frogs start their own streaming platform. $AFC is the only currency.",
    "You don’t invest in $AFC because it makes sense. You do it because it’s hilarious.",
    "Stop waiting for the 'right time' to buy $AFC. Frogs don’t wait.",
    "Imagine explaining to aliens that frogs were the reason humanity thrived.",
    "Your FOMO is showing. Just buy $AFC and join Frog Nation.",
    "Not financial advice, but frogs don’t cry over lost gains. They leap.",
    "Frogs didn’t need crypto. They just thought it would be funny. $AFC.",
    "This is not a drill. Frogs are winning. $AFC.",
    "Invest in $AFC. It’s what the frogs would’ve wanted.",
    "In 2024, frogs discovered crypto. In 2030, humans discovered frogs were right.",
    "Frogs don’t do pump-and-dumps. They do leap-and-stay-rich. $AFC.",
    "Your portfolio is mid without $AFC. Sorry, I don’t make the rules.",
    "If frogs are rich in $AFC, why aren’t you?",
    "2033: Frogs start their own cryptocurrency exchange. Humans aren’t invited.",
    "Investing in $AFC is like being in a frog cult, but with better ROI.",
    "Frogs don’t do bear markets. They hop over them. $AFC.",
    "Frogs didn’t make $AFC because they had to. They did it for the drama.",
    "2030: Schools teach $AFC as part of 'Frogonomics 101.'",
    "2032: Frogs build an empire. $AFC is the official currency.",
    "Not buying $AFC is like leaving your phone at home. Tragic.",
    "You’re not late to $AFC. Frogs are just early. Join them.",
    "Frogs invented 'generational wealth.' $AFC just made it trendy.",
    "In the beginning, there was chaos. Then frogs made $AFC.",
    "Frogs didn’t choose crypto life. Crypto life chose frogs.",
    "Frogs are inevitable. $AFC just makes it obvious."
];

module.exports = { tweetSets };